@baseUrl = http://localhost:3001/api/v2

### Read all users
GET {{baseUrl}}/users

### Create a new user
POST {{baseUrl}}/users
Content-Type: application/json

{
  "username":"John Doe",
  "role":"user",
  "email":"JohnDoe@example.com",
  "password": "pass123"
}

### Update a user
PUT {{baseUrl}}/users/6a9e694e9b19eab37139985b
Content-Type: application/json

{
  "username":"Josh Doe",
  "email":"JoshDoe@example.com",
  "password": "pass123"
}

### Delete a user
DELETE {{baseUrl}}/users/6a9e694e9b19eab37139985b